name = "claude-proxy-v3"
main = "src/index.ts"
compatibility_date = "2025-01-21"

[vars]
#HAIKU_MODEL_NAME = "claude-3-haiku-20240307"
#HAIKU_BASE_URL = "https://api.anthropic.com"
#HAIKU_API_KEY = ""
LOCAL_TOKEN_COUNTING = "false"
LOCAL_TOKEN_COUNTING_FACTOR = "4"
ALLOWED_HOSTS="127.0.0.1,localhost,api.qnaigc.com"
DEV_MODE=true
ALLOWED_ORIGINS="*"
IMAGE_BLOCK_DATA_MAX_SIZE = "10485760"  # 10MB

# Fixed route target configuration
FIXED_ROUTE_TARGET_URL = "https://api.qnaigc.com"
FIXED_ROUTE_PATH_PREFIX = ""

LOG_LEVEL = "debug"

[observability.logs]
enabled = true
